export const Mobile_WORD = [
  [
    { main: "چ", side: ["1", "۱"] },
    { main: "ج", side: ["2", "۲"] },
    { main: "جٰ", side: ["3", "۳"] },
    { main: "خ", side: ["4", "۴"] },
    { main: "هـ", side: ["5", "۵"] },
    { main: "غ", side: ["ڠ", "6", "۶"] },
    { main: "ٯ", side: ["7", "۷"] },
    { main: "ڧ", side: ["8", "۸"] },
    { main: "ق", side: ["9", "۹"] },
    { main: "ە", side: ["ەٕ", "0", "۰"] },
    { main: "ۀ", side: [""] },
  ],
  [
    { main: "گ", side: [""] },
    { main: "ک", side: ["ݣ"] },
    { main: "م", side: [""] },
    { main: "ن", side: [""] },
    { main: "ت", side: [""] },
    { main: "ا", side: ["آ"] },
    { main: "ب", side: [""] },
    { main: "ل", side: [""] },
    { main: "ي", side: [""] },
    { main: "س", side: [""] },
    { main: "ش", side: [""] },
  ],
  [
    { main: "پ", side: ["ݐ"] },
    { main: "و", side: [""] },
    { main: "ۋ", side: [""] },
    { main: "ۈ", side: ["ۊ"] },
    { main: "د", side: ["ڌ"] },
    { main: "ر", side: [""] },
    { main: "ز", side: ["ژ"] },
    { main: "ې", side: ["ࢨ"] },
    { main: "ئ", side: [""] },
    { main: "ۇ", side: ["ؤ"] },
    { main: "remove", side: [""] },
  ],
];

export const extraRow = [
  { main: "↵", action: "enter" },
  { main: "␣", action: "space" },
  { main: "_", action: "half-space" },
  { main: ".", action: "dot" },
  { main: ",", action: "comma" },
];
