export const Mobile_WORD = [
  [
    { main: "چ", side: ["1", "۱"] },
    { main: "ج", side: ["2", "۲"] },
    { main: "جٰ", side: ["3", "۳"] },
    { main: "خ", side: ["4", "۴"] },
    { main: "هـ", side: ["5", "۵"] },
    { main: "غ", side: ["6", "ڠ", "۶"], bottom: "ڠ" },
    { main: "ٯ", side: ["7", "۷"] },
    { main: "ڧ", side: ["8", "۸"] },
    { main: "ق", side: ["9", "۹"] },
    { main: "ە", side: ["ەٕ", "0", "۰"] },
    { main: "ۀ", side: [] },
  ],
  [
    { main: "گ", side: [] },
    { main: "ک", side: ["ݣ"] },
    { main: "م", side: [] },
    { main: "ن", side: [] },
    { main: "ت", side: [] },
    { main: "ا", side: ["آ"] },
    { main: "ب", side: [] },
    { main: "ل", side: [] },
    { main: "ي", side: [] },
    { main: "س", side: [] },
    { main: "ش", side: [] },
  ],
  [
    { main: "remove", side: [] },
    { main: "پ", side: ["ݐ"] },
    { main: "و", side: [] },
    { main: "ۋ", side: [] },
    { main: "ۈ", side: ["ۊ"] },
    { main: "د", side: ["ڌ"] },
    { main: "ر", side: [] },
    { main: "ز", side: ["ژ"] },
    { main: "ې", side: ["ࢨ"] },
    { main: "ئ", side: [] },
    { main: "ۇ", side: ["ؤ"] },
  ],
];

export const extraRow = [
  { main: "↳", action: "enter", cls: "text-[25px]" },
  { main: ".", action: "dot", cls: "text-[22px] pb-1" },
  { main: "⇼", action: "half-space", cls: "text-[30px] pb-1" },
  { main: "🌐", action: "lang" },
  { main: "␣", action: "space", cls: "flex-3 text-[30px] pb-4" },
  { main: ",", action: "comma", cls: "text-[22px] pb-2" },
  { main: "?123", action: "symbols", cls: "flex-2 text-[16px]" },
];
